export const siteMetadata = {
  title: "Fullstack Portfolio",
  siteUrl: "https://daniel-portfolio-gatsby-ts-contentful.netlify.app",
  description:
    "Portfolio Gatsby & Contentful powered website where I present myself and show my skills on different kind of projects and using a wide range of effective web design technologies.",
  image: "/homeImage.png",
  linkedInUsername: "daniel-b-ouattara-677146ab",
  twitterUsername: "@danielOuattara",
  name: "Daniel Ouattara",
  date: "Sept. 2023",
  aboutMe: {
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Animi commodiaperiam officiis nostrum maxime reprehenderit, totam eaque corporisrepudiandae soluta quos neque omnis dolore quibusdam aliquam,consectetur excepturi error suscipit.",
    stack: [
      "html",
      "javascript",
      "typescript",
      "node",
      "deno",
      "express",
      "postgresql",
      "mongodb",
      "css",
      "sass",
      "react",
      "vue",
      "gatsby",
      "next",
    ],
    image: "./src/assets/images/hero2.svg",
  },
};
