import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Layout } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home | Portfolio",
  description: "Generated by create next app",
  openGraph: {
    title: "Daniel's Portfolio, FullStack Developer",
    description:
      "This website is a portfolio where I present my skills as a fullstack web development. One can find many of the projects or websites I created sometimes from scratch and sometimes from existing projects/websites that I updated to feat my needs and my requirements",
    url: "https://daniel-portfolio-next-ts-contentful.vercel.app/",
    siteName: "daniel's portfolio",
    images: [
      {
        url: "https://daniel-portfolio-next-ts-contentful.vercel.app/home-2.png", // Image for Open Graph previews
        width: 1200,
        height: 630,
        alt: "image showing website home page",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image", // 'summary', 'summary_large_image', etc.
    title: "Daniel's Portfolio, FullStack Developer",
    description:
      "This website is a portfolio where I present my skills as a fullstack web development. One can find many of the projects or websites I created sometimes from scratch and sometimes from existing projects/websites that I updated to feat my needs and my requirements",
    // images: ["https://yourwebsite.com/twitter-image.jpg"], // Twitter-specific image
    images: [
      "https://daniel-portfolio-next-ts-contentful.vercel.app/home-2.png",
    ], // Twitter-specific image
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
