import type { Metadata } from "next";
import { Inter, Julee } from "next/font/google";
import "./globals.css";
import { Layout } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home | Portfolio",
  description: "Generated by create next app",
  openGraph: {
    title: "Daniel's Portfolio, FullStack Developer",
    description: "A brief description of your site",
    url: "https://daniel-portfolio-next-ts-contentful.vercel.app/",
    siteName: "daniel's portfolio",
    images: [
      {
        url: "https://daniel-portfolio-next-ts-contentful.vercel.app/home.png", // Image for Open Graph previews
        width: 1200,
        height: 630,
        alt: "Your Image Alt Text",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image", // 'summary', 'summary_large_image', etc.
    title: "Daniel's Portfolio, FullStack Developer",
    description: "A brief description of your site",
    images: ["https://yourwebsite.com/twitter-image.jpg"], // Twitter-specific image
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-EN">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
